apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "nodes", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: backstage-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: backstage-cluster-role
  apiGroup: rbac.authorization.k8s.io
