apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-devops
  description: DevOps Team responsible for infrastructure
spec:
  type: team
  profile:
    displayName: "DevOps Team"
    email: devops@example.com
  children: []
